version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: lasercraft-db
    environment:
      POSTGRES_DB: lasercraft
      POSTGRES_USER: lasercraft_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lasercraft-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: lasercraft-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - lasercraft-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lasercraft-app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://lasercraft_user:your_secure_password@postgres:5432/lasercraft
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    networks:
      - lasercraft-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: lasercraft-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - lasercraft-network

volumes:
  postgres_data:
  redis_data:

networks:
  lasercraft-network:
    driver: bridge